# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.CharField(max_length=50)),
                ('a_age', models.IntegerField()),
                ('a_gender', models.CharField(max_length=50)),
                ('a_color', models.CharField(max_length=50)),
                ('a_bread', models.CharField(max_length=500)),
                ('a_address', models.TextField(max_length=500)),
                ('vaccinated', models.CharField(max_length=100)),
                ('a_img', models.FileField(max_length=500, null=True, upload_to='jeeva/')),
            ],
        ),
    ]
