# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.TextField(max_length=500)),
                ('quantity', models.PositiveIntegerField()),
                ('userName', models.CharField(max_length=100)),
                ('userContact', models.PositiveIntegerField()),
                ('userAddress', models.TextField(max_length=500)),
                ('findingDate', models.DateField()),
            ],
        ),
    ]
