# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address1', models.TextField(max_length=500)),
                ('address2', models.TextField(max_length=500)),
                ('age', models.PositiveIntegerField()),
                ('ZipCode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
                ('contactPref', models.CharField(max_length=100)),
                ('aboutThem', models.TextField(max_length=500)),
            ],
        ),
    ]
