# Generated by Django 4.1.7 on 2023-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('wattsapp', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=100)),
                ('contactShare', models.CharField(max_length=100)),
                ('Allergy', models.CharField(max_length=100)),
                ('daysAttending', models.CharField(max_length=100)),
                ('activities', models.CharField(max_length=100)),
                ('about', models.TextField(default='not given', max_length=100)),
            ],
        ),
    ]
